name: github_repo_plus
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.3
  get_it: ^7.2.0
  intl: ^0.17.0
  easy_localization: ^3.0.0
  http_interceptor: ^1.0.1
  logger: ^1.1.0
  equatable: ^2.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/translations/
